package com.harmoni.pos.customer.domain.model;

import com.harmoni.pos.customer.domain.exception.InvalidCustomerSessionException;
import lombok.Getter;

import java.time.Instant;
import java.util.Objects;

/**
 * An ordering session bound to a customer, created from a given source
 * (e.g. a table QR code or an AI chat).
 * <p>
 * A session starts {@link CustomerSessionStatus#OPEN} and can be moved to
 * {@link CustomerSessionStatus#CLOSED} exactly once via {@link #close()}.
 */
@Getter
public class CustomerSession {

    private Long id;
    private final Long customerId;
    private final String sessionToken;
    private final CustomerSessionSource source;
    private CustomerSessionStatus status;
    private final Instant createdAt;
    private Instant updatedAt;

    public CustomerSession(Long id, Long customerId, String sessionToken, CustomerSessionSource source,
                           CustomerSessionStatus status, Instant createdAt, Instant updatedAt) {
        this.id = id;
        this.customerId = customerId;
        this.sessionToken = sessionToken;
        this.source = source;
        this.status = status;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    /**
     * Creates a new {@link CustomerSessionStatus#OPEN} session without an id
     * and timestamps (ready to be persisted).
     *
     * @param customerId   the owning customer
     * @param source       where the session originates (required)
     * @param sessionToken a unique session token generated by the backend (required, non-blank)
     * @return a new open session
     * @throws NullPointerException     if {@code source} is null
     * @throws IllegalStateException    if {@code sessionToken} is blank
     */
    public static CustomerSession create(Long customerId, CustomerSessionSource source, String sessionToken) {
        Objects.requireNonNull(source, "Session source is required");
        if (sessionToken == null || sessionToken.isBlank()) {
            throw new IllegalStateException("Session token must be generated by the backend");
        }
        return new CustomerSession(null, customerId, sessionToken, source, CustomerSessionStatus.OPEN, null, null);
    }

    /**
     * Marks the session as {@link CustomerSessionStatus#CLOSED}.
     *
     * @throws InvalidCustomerSessionException if the session is already closed
     */
    public void close() {
        if (this.status == CustomerSessionStatus.CLOSED) {
            throw new InvalidCustomerSessionException("Session " + id + " is already closed");
        }
        this.status = CustomerSessionStatus.CLOSED;
    }

    /**
     * @return {@code true} while the session is still {@link CustomerSessionStatus#OPEN}
     */
    public boolean isOpen() {
        return status == CustomerSessionStatus.OPEN;
    }
}
